[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
backend = { path = "../backend" }
strum = "0.26"
strum_macros = "0.26"
getopts = "0.2"
args = "2.2.0"
serde = "1.0"